version: '3.4'
services:
  meilisearch:
    image: getmeili/meilisearch
    command: ./meilisearch --master-key=masterKey --no-analytics=true
    volumes:
      - 'sailmeilisearch:/data.ms'
    ports:
        -   target: 7700
            published: 7700
            protocol: tcp

volumes:
  sailmeilisearch:
      driver: local

